name: Deploy FP Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-fp-backend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: vedangpaithankar/foodysparadise:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull vedangpaithankar/foodysparadise:latest
      - name: Stop and remove existing container
        run: docker rm -f fp-container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name fp-container \
          -e MONGO_URI="${{ secrets.MONGO_URI }}" \
          vedangpaithankar/foodysparadise:latest
