name: Deploy FP FrontEnd

on:
  push:
    branches:
      - main
    paths:
      - 'FoodysParadise - FrontEnd/**'
      - '.github/workflows/deploy-fp-frontend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./FoodysParadise - FrontEnd
          file: ./FoodysParadise - FrontEnd/Dockerfile
          push: true
          tags: vedangpaithankar/foodysparadise-frontend:latest
          build-args: |
            REACT_APP_SERVER=${{ secrets.REACT_APP_SERVER }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull vedangpaithankar/foodysparadise-frontend:latest
      - name: Stop and remove existing container
        run: docker rm -f fp-frontend-container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:80 --name fp-frontend-container \
          -e REACT_APP_SERVER="${{ secrets.REACT_APP_SERVER }}" \
          vedangpaithankar/foodysparadise-frontend:latest